# Generated by Django 5.2.4 on 2025-07-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstablishmentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('physical_location', models.CharField(max_length=255)),
                ('town', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('gps_coordinates', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('telephone', models.CharField(max_length=50)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_designation', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(max_length=254)),
                ('kesic_code', models.CharField(max_length=10)),
                ('kesic_description', models.CharField(max_length=255)),
                ('commercial_space_status', models.CharField(choices=[('solely_owned', 'Solely Owned'), ('jointly_owned', 'Jointly Owned'), ('rented', 'Rented')], max_length=20)),
                ('has_branches', models.BooleanField(default=False)),
                ('number_of_branches', models.PositiveIntegerField(blank=True, null=True)),
                ('is_member_of_association', models.BooleanField(default=False)),
                ('other_association_name', models.CharField(blank=True, max_length=255, null=True)),
                ('year_started_operations', models.PositiveIntegerField()),
                ('achievements', models.TextField(blank=True, null=True)),
                ('government_ownership_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('kenyan_citizens_ownership_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('non_citizens_ownership_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ownership_type', models.CharField(choices=[('sole_proprietorship', 'Sole Proprietorship'), ('partnership', 'Partnership'), ('private_ltd', 'Private Limited Company'), ('public_ltd', 'Public Limited Company'), ('joint_venture', 'Joint Venture'), ('cooperative', 'Cooperative'), ('parastatal', 'Parastatal/State Corporation'), ('county_gov', 'County Government'), ('national_gov', 'National Government'), ('other', 'Other')], max_length=30)),
                ('other_ownership_type', models.CharField(blank=True, max_length=255, null=True)),
                ('has_agpo_certificate', models.BooleanField(default=False)),
                ('agpo_category', models.CharField(blank=True, choices=[('women', 'Women Owned'), ('youth', 'Youth Owned'), ('pwds', 'PWDs Owned')], max_length=10, null=True)),
                ('enjoyed_tax_incentive', models.BooleanField(default=False)),
                ('tax_incentive_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('associations', models.ManyToManyField(blank=True, to='manufacturers.association')),
            ],
        ),
    ]
