# Generated by Django 5.2.4 on 2025-07-09 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('managerial', 'Managerial/Executive'), ('technical', 'Technical/Professional'), ('skilled', 'Skilled'), ('semi_skilled', 'Semi-skilled'), ('unskilled', 'Unskilled')], max_length=20)),
                ('male', models.PositiveIntegerField()),
                ('female', models.PositiveIntegerField()),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_levels', to='manufacturers.establishmentprofile')),
            ],
        ),
    ]
