# Generated by Django 5.2.4 on 2025-07-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0002_employees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='female',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='male',
        ),
        migrations.AddField(
            model_name='employees',
            name='adults_35_plus_female',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employees',
            name='adults_35_plus_male',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employees',
            name='employee_type',
            field=models.CharField(choices=[('regular', 'Regular/Permanent'), ('casual', 'Casual'), ('working_owners', 'Working Proprietors/Partners/Directors')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='pwds_female',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employees',
            name='pwds_male',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employees',
            name='youth_female',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employees',
            name='youth_male',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
