# Generated by Django 5.2.4 on 2025-07-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0003_remove_employees_female_remove_employees_male_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='adults_35_plus_female',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='adults_35_plus_male',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='pwds_female',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='pwds_male',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='youth_female',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='youth_male',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='establishmentprofile',
            name='name',
            field=models.CharField(),
        ),
    ]
