# Generated by Django 5.2.4 on 2025-07-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0004_alter_employees_adults_35_plus_female_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishmentprofile',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
