# Generated by Django 5.2.4 on 2025-07-09 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0005_alter_establishmentprofile_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'verbose_name': 'Employee Record', 'verbose_name_plural': 'Employee Records'},
        ),
        migrations.RemoveField(
            model_name='employees',
            name='adults_35_plus_female',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='adults_35_plus_male',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='employee_type',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='pwds_female',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='pwds_male',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='youth_female',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='youth_male',
        ),
        migrations.AddField(
            model_name='employees',
            name='casual_female',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='casual_male',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='category',
            field=models.CharField(choices=[('youth', 'Youth (<35)'), ('adult', 'Adult (≥35)'), ('pwd', 'Persons with Disability')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='proprietor_female',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='proprietor_male',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='regular_female',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='regular_male',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='year',
            field=models.PositiveIntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='employees',
            name='establishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturers.establishmentprofile'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='level',
            field=models.CharField(choices=[('executive', 'Managerial/Executive'), ('professional', 'Technical/Professional'), ('skilled', 'Skilled'), ('semi_skilled', 'Semi-skilled'), ('unskilled', 'Unskilled')], max_length=20),
        ),
    ]
