# Generated by Django 5.2.4 on 2025-07-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0006_alter_employees_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='category',
            field=models.CharField(choices=[('youth', 'Youth (<35)'), ('adult', 'Adult (≥35)'), ('proprietors', 'Proprietors')], max_length=100),
        ),
    ]
