# Generated by Django 5.2.4 on 2025-07-09 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0008_rename_casual_female_employees_casual_females_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hs_code', models.CharField(max_length=50, verbose_name='HS Code')),
                ('quantity_local', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('quantity_imported', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('unit', models.CharField(choices=[('kg', 'Kilograms'), ('ltr', 'Litres'), ('pcs', 'Pieces'), ('ton', 'Tons')], max_length=10)),
                ('year', models.PositiveIntegerField(default=2024)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturers.establishmentprofile')),
            ],
            options={
                'verbose_name': 'Raw Material',
                'verbose_name_plural': 'Raw Materials',
            },
        ),
    ]
