# Generated by Django 5.2.4 on 2025-07-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0009_rawmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='quantity_imported',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='quantity_local',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
