# Generated by Django 5.2.4 on 2025-07-09 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0010_alter_rawmaterial_quantity_imported_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_type', models.CharField(choices=[('coal', 'Coal (Tonne)'), ('water', 'Water (Cubic meters)'), ('wood_fuel', 'Wood Fuel (Tonne)'), ('gas_lpg', 'Gas (LPG) (Cubic meters)'), ('electricity_solar', 'Electricity - Solar (KWh)'), ('electricity_wind', 'Electricity - Wind (KWh)'), ('electricity_kplc', 'Electricity - KPLC (KWh)'), ('petrol', 'Petrol (Litre)'), ('diesel', 'Diesel (Litre)'), ('kerosene', 'Kerosene (Litre)'), ('biogas', 'Bio-gas (Cubic meters)'), ('charcoal', 'Charcoal (Tonne)'), ('other', 'Other (Specify)')], max_length=30)),
                ('other_utility_name', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=12)),
                ('value_ksh', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_capacity_required', models.DecimalField(decimal_places=2, max_digits=12)),
                ('satisfaction_level', models.IntegerField(choices=[(1, 'Very Satisfied'), (2, 'Satisfied'), (3, 'Neutral'), (4, 'Dissatisfied'), (5, 'Very Dissatisfied')])),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utility_consumptions', to='manufacturers.establishmentprofile')),
            ],
        ),
    ]
