# Generated by Django 5.2.4 on 2025-07-09 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0011_utilityconsumption'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnOperatingCapacityReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('primary', 'Primary Product'), ('secondary', 'Secondary Product')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('hs_code', models.CharField(max_length=20)),
                ('quantity_produced', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(max_length=50)),
                ('max_production_capacity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('operated_at_optimal_capacity', models.BooleanField(blank=True, null=True)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='manufacturers.establishmentprofile')),
                ('reasons_for_not_operating', models.ManyToManyField(blank=True, to='manufacturers.unoperatingcapacityreason')),
            ],
        ),
    ]
