# Generated by Django 5.2.4 on 2025-07-09 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0012_unoperatingcapacityreason_production'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_type', models.CharField(choices=[('local', 'Local'), ('export', 'Export')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(max_length=50)),
                ('value_ksh', models.DecimalField(decimal_places=2, max_digits=15)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='manufacturers.establishmentprofile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='manufacturers.production')),
            ],
        ),
    ]
