# Generated by Django 5.2.4 on 2025-07-09 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0014_solidwastedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteWaterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_type', models.CharField(choices=[('hazardous', 'Hazardous Water'), ('liquid', 'Liquid Waste / Waste Water')], max_length=20)),
                ('collected', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('treated', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recycled', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disposed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturers.establishmentprofile')),
            ],
        ),
    ]
