# Generated by Django 5.2.4 on 2025-07-09 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0016_wastemanagementcost'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentConservationActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=255)),
                ('amount_spent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conservation_activities', to='manufacturers.establishmentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TechnologiesUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_data', models.BooleanField(default=False)),
                ('cloud_computing', models.BooleanField(default=False)),
                ('artificial_intelligence', models.BooleanField(default=False)),
                ('internet_of_things', models.BooleanField(default=False)),
                ('advanced_robotics', models.BooleanField(default=False)),
                ('additive_manufacturing', models.BooleanField(default=False)),
                ('ar_vr', models.BooleanField(default=False)),
                ('other_4ir_tech', models.CharField(blank=True, max_length=255, null=True)),
                ('waste_reduction_tech_in_use', models.BooleanField(default=False)),
                ('renewable_energy', models.BooleanField(default=False)),
                ('waste_management', models.BooleanField(default=False)),
                ('decarbonization', models.BooleanField(default=False)),
                ('emission_control', models.BooleanField(default=False)),
                ('sustainable_materials', models.BooleanField(default=False)),
                ('energy_efficiency', models.BooleanField(default=False)),
                ('electric_vehicles', models.BooleanField(default=False)),
                ('green_cloud_tech', models.BooleanField(default=False)),
                ('other_green_tech', models.CharField(blank=True, max_length=255, null=True)),
                ('contributes_to_circular_economy', models.BooleanField(default=False)),
                ('product_design', models.BooleanField(default=False)),
                ('resource_recovery', models.BooleanField(default=False)),
                ('business_model_innovation', models.BooleanField(default=False)),
                ('use_recycled_inputs', models.BooleanField(default=False)),
                ('waste_to_value', models.BooleanField(default=False)),
                ('industrial_symbiosis', models.BooleanField(default=False)),
                ('eco_design_packaging', models.BooleanField(default=False)),
                ('consumer_awareness', models.BooleanField(default=False)),
                ('other_circular', models.CharField(blank=True, max_length=255, null=True)),
                ('reduce', models.BooleanField(default=False)),
                ('reuse', models.BooleanField(default=False)),
                ('recycle', models.BooleanField(default=False)),
                ('recover', models.BooleanField(default=False)),
                ('none_of_4rs', models.BooleanField(default=False)),
                ('establishment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technologies_used', to='manufacturers.establishmentprofile')),
            ],
        ),
    ]
